### ISSUE TITLE
View error: undefined is not an object (evaluating 'i.split')

### ISSUE THREAD

**Issue by mvshmakov** [iterative/studio-support#34]
The issue happens on the view page and results in the full page error.

**Comment by demirhere** [comment]
Is there an update or a temporary workaround to this at least until the issue is resolved? We haven't been able to access the project in Studio since this issue.

<img width="1437" alt="Screen Shot 2021-09-30 at 1 43 00 PM" src="https://user-images.githubusercontent.com/40176533/135449019-90fee03d-c8ef-4200-abe5-ae202282d027.png">

**Comment by mvshmakov** [comment]
Hello, @demirhere!
Thanks for the report, we are on it and expect a fix to be shipped very soon. I'll let you know about it, sorry for the inconvenience.

**Comment by mvshmakov** [comment]
@demirhere @cagdasbas the fix is shipped already and we can't see any problems of this type right now. Please, let me know if the problem still exists, or feel free to create a GitHub issue yourself!
