### ISSUE TITLE
Metrics not showing if output is too big

### ISSUE THREAD

**Issue by karpatika92** [iterative/studio-support#41]
#  Description

I am using DVC Studio to track metrics of my project. The outputs of the model training stage are 
* a csv that contains the test set predictions
* the model
* some plots including a confusion matrix and some linecharts
* a full metrics json that is traced as an output, not a metric (this has too many fields, and is too detailed for display)
* compact_metrics.json that is traced as a metric

When I run the training with the full dataset, DVC Studio breaks, anddoes not display the confusion matrix, and some of the metrics are missing too. (screenshot attached). the UI says that one big file failed to parse. Everything shows up in GitHub & CML though. 

When I limit the size of the dataset, everything works as expected. 

I suspect that the issue is that the confusion matrix input file and the test set predictions are too big for DVC Studio (they are about 10 - 20 MB, around 100-200k lines at most), so Studio does not load them.

Feature request:
* display which files are too big, and the ability to set a threshold

Keep up the great work, I love your products! :)

BR,

András K

**Comment by karpatika92** [comment]
![image](https://user-images.githubusercontent.com/30534285/142060321-cb46820c-c5d5-4dfe-8dc7-0911d6d0e956.png)

**Comment by Suor** [comment]
We have several limits on what we load. In your case it is expected to:
- not load bigger plots
- still load `compact_metrics.json` even in presence of skipped big files

I see that your `compact_metrics.json` resides in a nested dir, and there is at least one more metrics file there. In this case you may see empty or partially empty lines, like on your screenshot, because your metrics file has been renamed or moved. So may watch out for that.

We are currently working and discussing on raising the size limit for plots. We also always work on improving our error messages. And I will take a look at big files error specifically.
