### ISSUE TITLE
Do we need to track DVCLive files for Studio?

### ISSUE THREAD

**Issue by haimat** [iterative/studio-support#83]
We use DVCLive to track DVC experiments via Studio, so that I can monitor their progress in real time - that works fine so far. In Studio I can see the files from the `dvclive` folder on the project details page. Now if possible I would rather not track these files in Github, i.e. I would rather put the whole `dvclive` folder into my `.gitignore` file.

Therefore my question: Do I have to track the DVCLive files via Git so that Studio can work with them, or can I completely ignore these files for Git?

**Comment by dberenbaum** [comment]
We focus on saving everything in Git so that you have one source of truth from which you can reproduce the experiment. Do you mind explaining why you want to ignore these files?

Studio will continue to show the metrics shared in realtime, but you will lose out on other functionality. For example, if someone else checks out that commit, there is currently no way to retrieve those metrics back from Studio programmatically.

**Comment by shcheklein** [comment]
@haimat btw, by not tracking these files to you mean that you'd like to completely ignore them, or track them via DVC? (I think it's possible to put them into DVC, store on the remote storage).

**Comment by haimat** [comment]
Hmm... well, frankly I was not sure whether I really need those metrics later on. But I guess I forgot to think of the plots in DVC for which I need those files, as they depend on these metrics. Ok then never mind, I will keep them in Git :)
